place:
  offset_grasp:
  - -0.05   # x
  - 0.055   # z
  - 0.1     # angle
  offset_pregrasp:
  - -0.10   # x
  - 0.07    # z
  - -0.1    # angle
  polar_pos:
  - 0.235  # r
  - 0.0    # angle
  - 0.170  # z  